_target_: dataset.eval_mimicgen.EvalMimicgen
kwargs:
  data_root_dir: "robotic_data/mimicgen"
  interaction_root_dir: "robotic_data/interaction_data/coffee_d0"
  data_name: "mimicgen"
  data_list_names: "coffee_d0.json"
  interaction_list_names: "interaction_data_list.json"
  demo_number: 0
  image_shape: 224
